const INC = 'INC';
const INC_CUSTOM = 'INC_CUSTOM';
const DEC = 'DEC';
const RESET = 'RESET';

const INC_TWO = 'INC_TWO';
const INC_CUSTOM_TWO = 'INC_CUSTOM_TWO';
const DEC_TWO = 'DEC_TWO';
const RESET_TWO = 'RESET_TWO';
const ON_USERS_LOADED = 'ON_USERS_LOADED';
const ON_ADD_TO_BAD = 'ON_ADD_TO_BAD';
const ON_REMOVE_FROM_BAD = 'ON_REMOVE_FROM_BAD';

export {
    INC,
    INC_CUSTOM,
    DEC,
    RESET ,
    INC_TWO,
    INC_CUSTOM_TWO,
    DEC_TWO,
    RESET_TWO,
    ON_USERS_LOADED,
    ON_ADD_TO_BAD,
    ON_REMOVE_FROM_BAD,
}