const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';
const SET_PRODUCTS = 'SET_PRODUCTS';
const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART';
const REMOVE_PRODUCTS_FROM_CART = 'REMOVE_PRODUCTS_FROM_CART';
const ADD_PRODUCTS_TO_WISHLIST = 'ADD_PRODUCTS_TO_WISHLIST';
const REMOVE_PRODUCTS_FROM_WISHLIST = 'REMOVE_PRODUCTS_FROM_WISHLIST';

export {
  START_PRODUCTS_LOADING,
  END_PRODUCTS_LOADING,
  SET_PRODUCTS,
  ADD_PRODUCTS_TO_CART,
  REMOVE_PRODUCTS_FROM_CART,
  ADD_PRODUCTS_TO_WISHLIST,
  REMOVE_PRODUCTS_FROM_WISHLIST,
};
