const INC = 'INC';
const INC_CUSTOM = 'INC_CUSTOM';
const DEC = 'DEC';
const RESET = 'RESET';

const INC_TWO = 'INC_TWO';
const INC_CUSTOM_TWO = 'INC_CUSTOM_TWO';
const DEC_TWO = 'DEC_TWO';
const RESET_TWO = 'RESET_TWO';

const ON_USERS_LOADED = 'ON_USERS_LOADED';
const ON_ADD_TO_BAD = 'ON_ADD_TO_BAD';
const ON_REMOVE_FROM_BAD = 'ON_REMOVE_FROM_BAD';

const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';
const SET_PRODUCTS = 'SET_PRODUCTS';
const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART';
const REMOVE_PRODUCTS_FROM_CART = 'REMOVE_PRODUCTS_FROM_CART';
const ADD_PRODUCTS_TO_WISHLIST = 'REMOVE_PRODUCTS_FROM_CART';
const REMOVE_PRODUCTS_FROM_WISHLIST = 'REMOVE_PRODUCTS_FROM_CART';

export {
  INC,
  INC_CUSTOM,
  DEC,
  RESET,
  INC_TWO,
  INC_CUSTOM_TWO,
  DEC_TWO,
  RESET_TWO,
  ON_USERS_LOADED,
  ON_ADD_TO_BAD,
  ON_REMOVE_FROM_BAD,
  START_PRODUCTS_LOADING,
  END_PRODUCTS_LOADING,
  SET_PRODUCTS,
  ADD_PRODUCTS_TO_CART,
  REMOVE_PRODUCTS_FROM_CART,
  ADD_PRODUCTS_TO_WISHLIST,
  REMOVE_PRODUCTS_FROM_WISHLIST,
};
