const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';
const SET_PRODUCTS = 'SET_PRODUCTS';

export {START_PRODUCTS_LOADING, END_PRODUCTS_LOADING, SET_PRODUCTS};
